name: Lint

on:
  push:
    branches: [main]
    paths: ['**/config.json']
  pull_request:
    paths: ['**/config.json']
  workflow_dispatch:

jobs:
  check-duplicate-uuids:
    name: Check duplicate UUIDs
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@5a4ac9002d0be2fb38bd78e4b4dbde5606d7042f

      - name: Check for duplicate UUIDs
        run: .github/bin/check-duplicate-uuids.sh
